Audio Analysis Endpoint
rinukkusu/spotify-dart pull request #93
Opened 2021-01-26 22:33 UTC by Grabajuice

2021-02-17 06:02 UTC, rinukkusu requested changes
Again, looks great over all, and again please remove the merge commit from the change list. Wondering how that happened 🤔 

Thank you!

2021-02-17 06:02 UTC, rinukkusu commented on lib/src/models/audio_analysis.dart
> +List<TimeInterval> bars;
Please some more whitespace in this file ;)

2021-02-17 06:02 UTC, rinukkusu commented on lib/src/models/section.dart
> +  ///	Indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. This field will contain a 0 for “minor”, a 1 for “major”, or a -1 for no result.
Again with the long comments - you know the drill :)

2023-04-08 10:53 UTC, hayribakici commented
@rinukkusu I tried to fix the merge conflicts. I didn't know that it would inflict 79 files. Sorry about this mess. Any ideas on how to fix this?

2023-04-09 11:38 UTC, rinukkusu commented
@hayribakici I think there is nothing we can do really, with @Grabajuice not stepping into action. Probably easier to take the diff from this commit https://github.com/rinukkusu/spotify-dart/pull/93/commits/15adcf70e9666a04f42187b0d87f33a4d2a8e524 and reintegrate the code in a new branch from master.

2023-04-09 12:38 UTC, closed without merging